basic_search:
  chat_model_id: default_chat_model
  embedding_model_id: default_embedding_model
  prompt: prompts/basic_search_system_prompt.txt
cache:
  base_dir: cache
  type: file
chunks:
  group_by_columns:
  - id
  overlap: 200
  size: 2000
cluster_graph:
  max_cluster_size: 10
community_reports:
  graph_prompt: prompts/community_report_graph.txt
  max_input_length: 8000
  max_length: 2000
  model_id: default_chat_model
  text_prompt: prompts/community_report_text.txt
drift_search:
  chat_model_id: default_chat_model
  embedding_model_id: default_embedding_model
  prompt: prompts/drift_search_system_prompt.txt
  reduce_prompt: prompts/drift_search_reduce_prompt.txt
embed_graph:
  enabled: false
embed_text:
  model_id: default_embedding_model
  vector_store_id: default_vector_store
extract_claims:
  description: Any claims or facts that could be relevant to information discovery.
  enabled: false
  max_gleanings: 1
  model_id: default_chat_model
  prompt: prompts/extract_claims.txt
extract_graph:
  entity_types:
  - organization
  - person
  - geo
  - event
  max_gleanings: 0
  model_id: default_chat_model
  prompt: prompts/extract_graph.txt
extract_graph_nlp:
  async_mode: threaded
  text_analyzer:
    extractor_type: regex_english
global_search:
  chat_model_id: default_chat_model
  knowledge_prompt: prompts/global_search_knowledge_system_prompt.txt
  map_prompt: prompts/global_search_map_system_prompt.txt
  reduce_prompt: prompts/global_search_reduce_system_prompt.txt
input:
  file_type: text
  storage:
    base_dir: input
    type: file
local_search:
  chat_model_id: default_chat_model
  embedding_model_id: default_embedding_model
  prompt: prompts/local_search_system_prompt.txt
models:
  default_chat_model:
    api_base: http://localhost:11434/v1
    api_key: ollama
    async_mode: threaded
    auth_type: api_key
    concurrent_requests: 1
    max_retries: 10
    model: gpt-oss:20b-cloud
    model_provider: openai
    model_supports_json: true
    request_timeout: 3600.0
    requests_per_minute: null
    retry_strategy: exponential_backoff
    tokens_per_minute: null
    type: chat
  default_embedding_model:
    api_base: http://localhost:11434/v1
    api_key: ollama
    async_mode: threaded
    auth_type: api_key
    concurrent_requests: 25
    max_retries: 10
    model: nomic-embed-text
    model_provider: openai
    request_timeout: 600.0
    requests_per_minute: null
    retry_strategy: exponential_backoff
    tokens_per_minute: null
    type: embedding
output:
  base_dir: output
  type: file
reporting:
  base_dir: logs
  type: file
snapshots:
  embeddings: false
  graphml: false
summarize_descriptions:
  max_length: 500
  model_id: default_chat_model
  prompt: prompts/summarize_descriptions.txt
umap:
  enabled: false
vector_store:
  default_vector_store:
    container_name: default
    db_uri: output/lancedb
    type: lancedb
